server:
  port: 8090
spring:
  application:
    name: login-server-login
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以自定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
  dashboard:
    enabled: true
    path: /
#  rabbitmq:
#  host: 127.0.0.1
#  port: 5672
#  username: guest
#  password: guest
  management:
    endpoints:
    web:
    exposure:
    include: bus-refresh

    #建议暴露所有的端⼝
    management:
      endpoints:
      web:
      exposure:
      include: "*"
login-server-code:
  ribbon:
    ConnectTimeout: 5000
    ReadTimeout: 5000
